# Generated by Django 5.2.3 on 2025-06-28 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='maison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='location_api.maison'),
        ),
        migrations.AlterField(
            model_name='media',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='location_api.chambre'),
        ),
    ]
